"""SQLAlchemy Core tables that mirror the Alembic migrations.

Used to build queries, never to generate the schema: migrations are the source of truth. These
objects carry columns, types, defaults, primary and foreign keys. CHECK constraints, partial
indexes and the append-only trigger live only in the migration, where the database enforces them.
tests/db/test_schema_drift.py fails if this file and the migrated database disagree.
"""

from enum import StrEnum
from typing import Any

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg

from app.domain.enums import (
    ApprovalStatus,
    DueSource,
    ItemStatus,
    ItemType,
    OutboxStatus,
    Resolution,
    TeamRole,
)

metadata = sa.MetaData()


def _enum(enum: type[StrEnum], name: str) -> pg.ENUM:
    # create_type=False: the migration owns the type.
    return pg.ENUM(*[m.value for m in enum], name=name, create_type=False)


def _uuid_pk() -> sa.Column[Any]:
    return sa.Column(
        "id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.func.gen_random_uuid()
    )


def _now() -> sa.sql.elements.TextClause:
    return sa.text("now()")


team_role = _enum(TeamRole, "team_role")
item_type = _enum(ItemType, "item_type")
item_status = _enum(ItemStatus, "item_status")
resolution = _enum(Resolution, "resolution")
approval_status = _enum(ApprovalStatus, "approval_status")
due_source = _enum(DueSource, "due_source")
outbox_status = _enum(OutboxStatus, "outbox_status")

users = sa.Table(
    "users",
    metadata,
    _uuid_pk(),
    sa.Column("email", pg.CITEXT, nullable=False),
    sa.Column("name", sa.Text, nullable=False),
    sa.Column("password_hash", sa.Text, nullable=False),
    sa.Column("is_admin", sa.Boolean, nullable=False, server_default=sa.false()),
    sa.Column("failed_logins", sa.Integer, nullable=False, server_default=sa.text("0")),
    sa.Column("locked_until", sa.DateTime(timezone=True)),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=_now()),
    sa.Column("deactivated_at", sa.DateTime(timezone=True)),
)

teams = sa.Table(
    "teams",
    metadata,
    _uuid_pk(),
    sa.Column("key", sa.Text, nullable=False),
    sa.Column("name", sa.Text, nullable=False),
    sa.Column("description", sa.Text, nullable=False, server_default=sa.text("''")),
    sa.Column("item_seq", sa.Integer, nullable=False, server_default=sa.text("0")),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=_now()),
)

memberships = sa.Table(
    "memberships",
    metadata,
    sa.Column("team_id", pg.UUID(as_uuid=True), sa.ForeignKey("teams.id"), primary_key=True),
    sa.Column("user_id", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), primary_key=True),
    sa.Column("role", team_role, nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=_now()),
)

work_items = sa.Table(
    "work_items",
    metadata,
    _uuid_pk(),
    sa.Column("key", sa.Text, nullable=False),
    sa.Column("team_id", pg.UUID(as_uuid=True), sa.ForeignKey("teams.id"), nullable=False),
    sa.Column("number", sa.Integer, nullable=False),
    sa.Column("origin_team_id", pg.UUID(as_uuid=True), sa.ForeignKey("teams.id"), nullable=False),
    sa.Column("type", item_type, nullable=False),
    sa.Column("title", sa.Text, nullable=False),
    sa.Column("description", sa.Text, nullable=False, server_default=sa.text("''")),
    sa.Column("priority", sa.SmallInteger, nullable=False),
    sa.Column("status", item_status, nullable=False, server_default=sa.text("'new'")),
    sa.Column("resolution", resolution),
    sa.Column("resolution_note", sa.Text),
    sa.Column("duplicate_of_id", pg.UUID(as_uuid=True), sa.ForeignKey("work_items.id")),
    sa.Column("requester_id", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
    sa.Column("assignee_id", pg.UUID(as_uuid=True), sa.ForeignKey("users.id")),
    sa.Column("confidential", sa.Boolean, nullable=False),
    sa.Column("requires_approval", sa.Boolean, nullable=False),
    sa.Column("due_at", sa.DateTime(timezone=True)),
    sa.Column("due_source", due_source, nullable=False, server_default=sa.text("'auto'")),
    sa.Column("sla_breached_at", sa.DateTime(timezone=True)),
    sa.Column("last_event_id", sa.BigInteger),
    sa.Column(
        "last_activity_at", sa.DateTime(timezone=True), nullable=False, server_default=_now()
    ),
    sa.Column("version", sa.Integer, nullable=False, server_default=sa.text("1")),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=_now()),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=_now()),
    sa.Column("resolved_at", sa.DateTime(timezone=True)),
    sa.Column("closed_at", sa.DateTime(timezone=True)),
    # Generated by Postgres (SPEC 8). Computed() keeps it out of INSERT and UPDATE statements.
    sa.Column(
        "search",
        pg.TSVECTOR,
        sa.Computed(
            "setweight(to_tsvector('simple'::regconfig, coalesce(key, '')), 'A') || "
            "setweight(to_tsvector('english'::regconfig, title), 'A') || "
            "setweight(to_tsvector('english'::regconfig, coalesce(description, '')), 'B')",
            persisted=True,
        ),
    ),
)

item_events = sa.Table(
    "item_events",
    metadata,
    sa.Column("id", sa.BigInteger, sa.Identity(always=True), primary_key=True),
    sa.Column("item_id", pg.UUID(as_uuid=True), sa.ForeignKey("work_items.id"), nullable=False),
    sa.Column("team_id", pg.UUID(as_uuid=True), sa.ForeignKey("teams.id"), nullable=False),
    sa.Column("actor_id", pg.UUID(as_uuid=True), sa.ForeignKey("users.id")),
    sa.Column("kind", sa.Text, nullable=False),
    sa.Column("item_version", sa.Integer, nullable=False),
    sa.Column("data", pg.JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
    sa.Column("reason", sa.Text),
    sa.Column("is_decision", sa.Boolean, nullable=False, server_default=sa.false()),
    sa.Column("request_id", sa.Text),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=_now()),
)

comments = sa.Table(
    "comments",
    metadata,
    sa.Column("id", sa.BigInteger, sa.Identity(always=True), primary_key=True),
    sa.Column("item_id", pg.UUID(as_uuid=True), sa.ForeignKey("work_items.id"), nullable=False),
    sa.Column("author_id", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
    sa.Column("body", sa.Text, nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=_now()),
)

approvals = sa.Table(
    "approvals",
    metadata,
    _uuid_pk(),
    sa.Column("item_id", pg.UUID(as_uuid=True), sa.ForeignKey("work_items.id"), nullable=False),
    sa.Column("status", approval_status, nullable=False, server_default=sa.text("'pending'")),
    sa.Column("requested_by", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
    sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False, server_default=_now()),
    sa.Column("request_note", sa.Text),
    sa.Column("subject_hash", sa.Text, nullable=False),
    sa.Column("decided_by", pg.UUID(as_uuid=True), sa.ForeignKey("users.id")),
    sa.Column("decided_at", sa.DateTime(timezone=True)),
    sa.Column("decision_note", sa.Text),
    sa.Column("invalidated_reason", sa.Text),
)

watchers = sa.Table(
    "watchers",
    metadata,
    sa.Column("item_id", pg.UUID(as_uuid=True), sa.ForeignKey("work_items.id"), primary_key=True),
    sa.Column("user_id", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), primary_key=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=_now()),
)

item_reads = sa.Table(
    "item_reads",
    metadata,
    sa.Column("user_id", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), primary_key=True),
    sa.Column("item_id", pg.UUID(as_uuid=True), sa.ForeignKey("work_items.id"), primary_key=True),
    sa.Column("last_read_version", sa.Integer, nullable=False),
    sa.Column("read_at", sa.DateTime(timezone=True), nullable=False, server_default=_now()),
)

notifications = sa.Table(
    "notifications",
    metadata,
    sa.Column("id", sa.BigInteger, sa.Identity(always=True), primary_key=True),
    sa.Column("user_id", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
    sa.Column("item_id", pg.UUID(as_uuid=True), sa.ForeignKey("work_items.id"), nullable=False),
    sa.Column("event_id", sa.BigInteger, sa.ForeignKey("item_events.id"), nullable=False),
    sa.Column("kind", sa.Text, nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=_now()),
    sa.Column("read_at", sa.DateTime(timezone=True)),
)

item_similar = sa.Table(
    "item_similar",
    metadata,
    sa.Column("item_id", pg.UUID(as_uuid=True), sa.ForeignKey("work_items.id"), primary_key=True),
    sa.Column(
        "similar_item_id", pg.UUID(as_uuid=True), sa.ForeignKey("work_items.id"), primary_key=True
    ),
    sa.Column("score", sa.REAL, nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=_now()),
)

idempotency_keys = sa.Table(
    "idempotency_keys",
    metadata,
    sa.Column("user_id", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), primary_key=True),
    sa.Column("key", sa.Text, primary_key=True),
    sa.Column("fingerprint", sa.Text, nullable=False),
    sa.Column("response_status", sa.Integer),
    sa.Column("response_body", pg.JSONB),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=_now()),
)

outbox = sa.Table(
    "outbox",
    metadata,
    sa.Column("id", sa.BigInteger, sa.Identity(always=True), primary_key=True),
    sa.Column("topic", sa.Text, nullable=False),
    sa.Column("payload", pg.JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
    sa.Column("dedupe_key", sa.Text),
    sa.Column("status", outbox_status, nullable=False, server_default=sa.text("'pending'")),
    sa.Column("attempts", sa.Integer, nullable=False, server_default=sa.text("0")),
    sa.Column("available_at", sa.DateTime(timezone=True), nullable=False, server_default=_now()),
    sa.Column("locked_until", sa.DateTime(timezone=True)),
    sa.Column("last_error", sa.Text),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=_now()),
    sa.Column("processed_at", sa.DateTime(timezone=True)),
)

sessions = sa.Table(
    "sessions",
    metadata,
    sa.Column("id", sa.Text, primary_key=True),
    sa.Column("user_id", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=_now()),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False, server_default=_now()),
    sa.Column("user_agent", sa.Text),
)
